project:
  type: book

book:
  cover-image: cover.png
  page-navigation: true
  title: "Business Science Practice"
  author: "Eddwin Cheteni"
  date: "2023/01/18"
  repo-url: https://github.com/eddychetz/business-science-book.git
  repo-actions: [edit, issue, source]
  downloads: [pdf, epub]
  sharing: [facebook, twitter]
  chapters:
    - index.qmd
    - intro.qmd
    - foundational.qmd
    - problem-solving.qmd
    - time-series.qmd
    - build-portfolio-tools.qmd
    - build-company-tools.qmd
    - summary.qmd
    - references.qmd
  # appendices:
  #   - tools.qmd
  #   - resources.qmd

comments:
  hypothesis: false
bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: cosmo
#   pdf:
#     documentclass: scrreprt
#     include-in-header:
#       text: |
#         \usepackage{makeidx}
#         \makeindex
#     include-after-body:
#       text: |
#         \printindex
# editor: visual

