project:
  type: book

book:
  page-navigation: true
  title: "Business Science Practice"
  author: "Eddwin Cheteni"
  date: "2023/01/18"
  chapters:
    - index.qmd
    - intro.qmd
    - data-desc.qmd
    - prob.qmd
    - summary.qmd
    - references.qmd
  # appendices:
  #   - tools.qmd
  #   - resources.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: darkly
      dark: cosmo
    code-copy: true
    code-fold: true
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
editor: visual

